### PR TITLE
feat : add karma as test runner.

### PR DESCRIPTION
**Pull request by MartinFerret**
Add karma as a test runner

### CODE REVIEW

**Comment by kolodny** [comment]
Cool, @MartinFerret can you add an example app that uses karma as a test runner to the repo as well so we have confidence everything is working as expectef?

**Comment by kolodny** [comment]
Looking over this again, can you not just import the vitest module when using karma? We should probably simplify all these adapters since there's probably only 5 lines difference between all of them

**Comment by MartinFerret** [comment]
Sure, There are some small differences between both Karma & Vitest files.

**Comment by kolodny** [comment]
Yeah that sounds good, the hardest part is getting the types to work across both.

**Comment by kolodny** [comment]
Closing for now

**Pull request closed without merging**
